# Generated by Django 5.0.2 on 2024-02-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Squares', '0002_square'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='purchase_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='squares_purchased',
            field=models.IntegerField(default=0),
        ),
    ]
