# Generated by Django 5.0.2 on 2024-02-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Squares', '0004_participant_squares_pending'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kc_score', models.IntegerField(default=0)),
                ('sf_score', models.IntegerField(default=0)),
                ('quarter_finalized', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='square',
            name='winning_quarters',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
