# Generated by Django 5.0.2 on 2024-02-09 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Squares', '0005_gamescore_square_winning_quarters'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamescore',
            options={'verbose_name_plural': 'GameScores'},
        ),
    ]
