# Generated by Django 5.0.2 on 2024-02-09 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Squares', '0006_alter_gamescore_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='square',
            name='winning_quarters',
        ),
        migrations.CreateModel(
            name='WinningQuarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Squares.gamescore')),
                ('square', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Squares.square')),
            ],
        ),
        migrations.AddField(
            model_name='square',
            name='game_scores',
            field=models.ManyToManyField(blank=True, through='Squares.WinningQuarter', to='Squares.gamescore'),
        ),
    ]
